ARDUINO_DIR=/usr/share/arduino
AVR_TOOLS_PATH=/usr/bin
TARGET=hello2
BOARD_TAG=mega
ARDUINO_PORT=/dev/ttyUSB0
AVRDUDE_CONF=$(ARDUINO_DIR)/hardware/tools/avrdude.conf
ARDUINO_LIBS = Servo CapSense IRremote Nunchuck Wire twi glcd

include  /usr/share/arduino/custom/Arduino.mk
